---
module_name: hashset
version: 0.1.0
hash: b2c5253e41abbef92c418966e248ad01
module_paths:
  - "${MODULES_PATH}"
modules:
  array_extensions:
    path: "${MODULES_PATH}/array_extensions"
    version: 0.1.0
  hash:
    path: "${MODULES_PATH}/hash"
    version: 0.1.0
  range:
    path: "${MODULES_PATH}/range"
    version: 0.1.0
