---
module_name: hashset
version: 0.1.0
hash: 401834d10278a3a4c7d431074874639c
module_paths:
  - "${MODULES_PATH}"
modules:
  range:
    path: "${MODULES_PATH}/prelude/range"
    version: 0.1.0
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
  hash:
    path: "${MODULES_PATH}/prelude/hash"
    version: 0.1.0
