---
module_name: hashset
version: 0.1.0
hash: e3bd019f074aa18063f3c488a09af4b0
module_paths:
  - ${MODULES_PATH}
modules:
  range:
    path: ${MODULES_PATH}/range
    version: 0.1.0
  hash:
    path: ${MODULES_PATH}/hash
    version: 0.1.0