---
module_name: hashmap
version: 0.1.0
hash: a2ae15d5323b45482fec6b081a25b9b3
module_paths:
  - "${MODULES_PATH}"
modules:
  hash:
    path: "${MODULES_PATH}/hash"
    version: 0.1.0
  range:
    path: "${MODULES_PATH}/range"
    version: 0.1.0
  array_extensions:
    path: "${MODULES_PATH}/array_extensions"
    version: 0.1.0
