---
module_name: hashmap
version: 0.1.0
hash: a2ee528aa57e5931fb0b9086e66ef0b2
module_paths:
  - ${MODULES_PATH}
modules:
  range:
    path: ${MODULES_PATH}/range
    version: 0.1.0
  hash:
    path: ${MODULES_PATH}/hash
    version: 0.1.0
