---
module_name: array_extensions
version: 0.1.0
hash: 32bb408e7cb0fc9cdaa20f622b20d571
module_paths:
  - "${MODULES_PATH}"
modules:
  range:
    path: "${MODULES_PATH}/prelude/range"
    version: 0.1.0
