---
module_name: string_extensions
version: 0.1.0
hash: 6539ef837e5662207ceacbd87424b29c
module_paths:
  - "${MODULES_PATH}"
modules:
  array_extensions:
    path: "${MODULES_PATH}/prelude/array_extensions"
    version: 0.1.0
